# Generated by Django 5.1.2 on 2024-10-30 16:48

import datetime
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Branches',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=221, null=True, verbose_name='Nomi')),
                ('created_at', models.DateTimeField(blank=True, default=datetime.datetime(2024, 10, 30, 21, 48, 46, 545051), null=True, verbose_name='Yaratilgan vaqti')),
            ],
            options={
                'verbose_name': 'Branch',
                'verbose_name_plural': 'Filiallar',
                'db_table': 'branch',
            },
        ),
        migrations.CreateModel(
            name='Ranks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=221, null=True, verbose_name='Nomi')),
                ('created_at', models.DateTimeField(blank=True, default=datetime.datetime(2024, 10, 30, 21, 48, 46, 545051), null=True, verbose_name='Yaratilgan vaqti')),
            ],
            options={
                'verbose_name': 'Rank',
                'verbose_name_plural': 'Lavozimlar',
                'db_table': 'rank',
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='F.I.Sh')),
                ('username', models.CharField(blank=True, max_length=100, null=True, verbose_name='Username')),
                ('phone', models.CharField(blank=True, max_length=100, null=True, verbose_name='Telefon raqam')),
                ('telegram_id', models.BigIntegerField(blank=True, null=True, unique=True, verbose_name='Telegram ID')),
                ('joined_at', models.DateTimeField(blank=True, default=datetime.datetime(2024, 10, 30, 21, 48, 46, 544051), null=True, verbose_name="Qo'shilgan vaqti")),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Foydalanuvchilar',
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='Questionnaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ish_muhiti_va_madaniyati', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='Ish muhiti va madaniyati')),
                ('rivojlanish_va_osish_imkoniyatlari', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name="Rivojlanish va o'sish imkoniyatlari")),
                ('ish_haqi_va_mukofotlar', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='Ish haqi va mukofotlar')),
                ('rahbariyat_bilan_munosabat', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='Rahbariyat bilan munosabat')),
                ('ish_muvozanati_va_farovonligi', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name="Ish muvozanati va farovonligi (Ish va hayot muvozanatiga e'tibor, stress darajasi, dam olish va tanaffuslar, ish yuklamasi)")),
                ('created_at', models.DateTimeField(blank=True, default=datetime.datetime(2024, 10, 30, 21, 48, 46, 545051), null=True, verbose_name='Yaratilgan vaqti')),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='questionnaire.branches', verbose_name='Filial')),
                ('rank', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='questionnaire.ranks', verbose_name='Lavozim')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='questionnaire.users', verbose_name='Foydalanuvchi')),
            ],
            options={
                'verbose_name': 'Questionnaire',
                'verbose_name_plural': 'Atvetlar',
                'db_table': 'questionnaire',
            },
        ),
    ]
