# Generated by Django 5.1.2 on 2024-10-30 16:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='phone',
        ),
        migrations.AlterField(
            model_name='branches',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 10, 30, 21, 54, 34, 587896), null=True, verbose_name='Yaratilgan vaqti'),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 10, 30, 21, 54, 34, 588892), null=True, verbose_name='Yaratilgan vaqti'),
        ),
        migrations.AlterField(
            model_name='ranks',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 10, 30, 21, 54, 34, 588892), null=True, verbose_name='Yaratilgan vaqti'),
        ),
        migrations.AlterField(
            model_name='users',
            name='joined_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 10, 30, 21, 54, 34, 587896), null=True, verbose_name="Qo'shilgan vaqti"),
        ),
    ]
